import React from "react";
import Head from "next/head";

function blackjack() {
  return (
    <div>
      <Head>
        <title>¿Cómo jugar Blackjack?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Aqui tenemos la pagina de blackjack</h1>
    </div>
  );
}

export default blackjack;
