import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Blackjack.module.css";

function blackjack() {
  return (
    <div className={styles.hero}>
      <Head>
        <title>¿Cómo jugar Blackjack?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.textDiv}>
        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Cómo jugar blackjack?</h1>

          <p className={styles.textP}>
            Si eres nuevo en el mundo de las apuestas, seguramente te has
            preguntado
            <h2 className={styles.seoH2}>¿como jugar al blackjack y ganar?</h2>O
            al menos habrás escuchado nombrar este juego en películas donde los
            protagonistas contaban cartas y lograban hacerse de una probabilidad
            estadística de ganarle a la casa.
          </p>

          <p className={styles.textP}>
            Si bien, <h2 className={styles.seoH2}>jugar al blackjack</h2>, es
            sencillo comparado con otros juegos de mayor complejidad, requiere
            estar muy al tanto del reglamento para saber qué movimiento es el
            más conveniente en cada caso. Se juega con cartas francesas y el
            número de barajas a utilizar puede variar entre 1 y 8 según la
            versión del juego.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Cómo jugar al blackjack online?</h1>

          <p className={styles.textP}>
            <h2 className={styles.seoH2}>Jugar online blackjack</h2> es mucho
            más sencillo de lo que imaginas. Es posible jugar hasta 5 manos a la
            vez y con 5 apuestas individuales y diferentes, siempre irás contra
            la banca.
          </p>

          <p className={styles.textP}>
            Si bien hay muchos botones disponibles para realizar la jugada, la
            mayor parte del tiempo los mas usados serán {'"'}pedir{'"'},{'"'}
            repartir{'"'} y {'"'}plantarse{'"'}. Todas las opciones que hay son:
          </p>

          <ul className={styles.list}>
            <li className={styles.ruletaListItem}>
              <strong>Repartir:</strong> El botón indica al sistema que reparta
              las cartas. Es en este momento que el jugador recibe sus cartas.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Pedir:</strong> Indica al sistema que debe entregar más
              cartas al jugador.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Plantarse:</strong> En esta opción no recibirás más cartas
              y te quedas con la puntuación obtenida.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Doblar:</strong> Indica al sistema que doblas la apuesta y
              recibes una carta. Esta opción permite duplicar la apuesta inicial
              si se cumplen las siguientes circunstancias
            </li>
            <li className={styles.ruletaListItem}>
              Una vez que se ha repartido las primeras dos cartas se puede
              añadir una apuesta adicional igual a la apuesta original y solo
              podrás recibir una carta extra para completar la jugada.
            </li>
            <li className={styles.ruletaListItem}>
              Otra variante del juego la posibilidad de doblar una vez que se
              divide, también es necesario tener en cuenta
            </li>
            <li className={styles.ruletaListItem}>
              Una vez que divides una mano en dos aportes o más puedes doblar la
              apuesta a la mesa.
            </li>
            <li className={styles.ruletaListItem}>
              Si una vez que divides, decides doblar se comenzarán a aplicar las
              normas habituales para la opción doblar para ese momento.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Dividir:</strong>Cuando tienes dos cartas iguales, tienes
              la opción de jugar dos manos en una ronda.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Nueva apuesta:</strong> Comienzas una nueva ronda.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Reapostar:</strong> vuelves a hacer la misma apuesta que
              en la ronda anterior
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Rendirse:</strong> Algunos juegos de blackjack dan la
              opción de rendirse la cual permite recuperar el 50% de la apuesta
              inicial cuando es inminente que ganara la banca.
            </li>
          </ul>

          <p className={styles.textP}>
            Si todas estas indicaciones no alcanzan y aun así tienes dudas,
            dentro de las páginas hay una sección de ayuda donde hay preguntas
            frecuentes que hacen los usuarios y de este modo se puede seguir
            adelante con el juego de manera fluida.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Cuál es el objetivo del juego?</h1>

          <p className={styles.textP}>
            Aquí te explicaremos el:{" "}
            <h2 className={styles.seoH2}>como jugar al 21 blackjack</h2>. Se
            reparten dos cartas a la vista. El juego consiste en aproximarse al
            21 sin pasarse de la cifra, pero es necesario sobrepasar el valor
            que tiene el crupier para poder ganar la partida. Se considera
            blackjack cuando obtienes 21 puntos con tan solo 2 cartas, un as y
            una J, Q o K. Estas últimas valen 10 y 11 puntos el as. En caso de
            no llegar a 21 será necesaria obtener más de 21 puntos para poder
            ganar la partida. Un ejemplo muy gráfico sucede si sumas 18 puntos
            con tus cartas, la casa ganará si tiene 19, 20 o 21 puntos. En caso
            de empate se te devolverá la apuesta.
          </p>
          <p className={styles.textP}>
            El objetivo del Blackjack es derrotar a la banca y para ello es
            necesario tener una mano mejor que la de la banca y que esta no
            supere 21 en su sumatoria total. También es posible que ganes con
            menos de 22, pero la banca debe superar los 21. En caso de que tu
            mano pase de 22 se dice que te has {'"'}pasado{'"'} y puedes perder
            todo el dinero que apostaste.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Cuál es la mejor mano del juego?</h1>

          <p className={styles.textP}>
            La mejor mano del Blackjack es el {'"'}Blackjack{'"'} y tiene un
            premio superior que el de cualquier jugada y puede estar compuesta
            por un as y cualquier otra carta con valor de 10, reyes, jotas o
            damas. Es una jugada prácticamente invencible a no ser que empate a
            la banca.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Es posible contar cartas en el Blackjack?
          </h1>
          <p className={styles.textP}>
            El hecho de ser uno de los pocos juegos en los que se da esta
            posibilidad, ha hecho que muchos adeptos al juego lo intenten para
            hacer más rentables sus apuestas. Pero los casinos están muy al
            tanto de esta posible práctica y eso hace que tengan la precaución
            de realizar un mezclado constante y un cambio de barajas para evitar
            que aquellos que intenten contar cartas, tengan éxito.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Se puede seguir una estrategia exitosa en el blackjack?
          </h1>
          <p className={styles.textP}>
            En este juego a diferencia de otros más simples como las{" "}
            <strong>máquinas tragamonedas</strong> y la <strong>ruleta</strong>,
            en la que solo basta con apretar un botón, tomar la decisión
            correcta ayudará a minimizar la ventaja del casino
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Puedo jugar blackjack en vivo?</h1>
          <p className={styles.textP}>
            Está es una de las opciones más atractivas cuando comienzas en este
            mundo es la posibilidad de tener todo el realismo del blackjack
            presencial de un casino físico, pero en forma digital.
          </p>

          <h2 className={styles.textHead}>¿Cómo jugar al blackjack en casa?</h2>
          <p className={styles.textP}>
            Muchos casinos tienen la opción de jugar en vivo con crupier reales,
            y esto sin abandonar la comodidad de tu hogar.
          </p>

          <p className={styles.textP}>
            Para asegurarte de que sean confiables te recomiendo verificar:
          </p>

          <ul className={styles.list}>
            <li className={styles.ruletaListItem}>
              que cuente con diferentes estilos de blackjack en su versión en
              vivo
            </li>
            <li className={styles.ruletaListItem}>
              que tenga buena calidad de transmisión para tener una experiencia
              sin cortes y con alto grado de realismo
            </li>
            <li className={styles.ruletaListItem}>
              Que la transmisión sea compatible con dispositivos móviles.
            </li>
          </ul>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>Consejos para jugadores novatos.</h1>

          <p className={styles.textP}>
            Si eres nuevo jugando al Blackjack es muy recomendable que sigas
            estos consejos:
          </p>

          <ul className={styles.list}>
            <li className={styles.ruletaListItem}>
              Puedes comenzar jugando de manera gratuita para familiarizarte con
              las reglas del juego.
            </li>
            <li className={styles.ruletaListItem}>
              Ten definida la cantidad de dinero que quieres gastar.
            </li>
            <li className={styles.ruletaListItem}>
              Analiza bien las reglas del juego para no tener sorpresas una vez
              iniciada la partida.
            </li>
            <li className={styles.ruletaListItem}>
              Observa bien los valores de las cartas del crupier.
            </li>
          </ul>

          <p className={styles.textP}>
            Este juego es uno de los más solicitados en
            <strong>casinos online</strong> de todo el mundo. Resulta muy
            atractivo y atraparte para sus usuarios más adeptos. Si quieres
            ingresar a jugar y aumentar tus probabilidades de hacer crecer tu
            dinero, puedes hacer clic aquí y comenzar tu partida.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            Como funciona el Black Jack en vivo 2021
          </h1>

          <p className={styles.textP}>
            Si te gusta lo mejor del mundo del casino físico, pero en el mundo
            digital, el blackjack online es la mejor opción
          </p>
          <p className={styles.textP}>
            El blackjack en vivo es muy confiable en la mayoría de los casinos
            serios, ya que cuenta con dealers en tiempo real que ayudan a que se
            puede mantener el realismo y combinar lo mejor de un casino
            presencial con uno digital.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Cómo funcionan los pagos en el blackjack en vivo?
          </h1>

          <p className={styles.textP}>
            Si en una de las primeras dos manos te toca blackjack con tus
            primeras dos manos se pagará con una proporción de 3 a 2 y las
            apuestas de {'"'}seguro{'"'} se pagarán 2 a 1 dependiendo de si el
            dealer tiene blackjack. Se puede doblar cualquier mano de dos cartas
            y dividir pares. Cuando se dividen ases.
          </p>

          <p className={styles.textP}>
            También existe una opción de apuestas adicionales que incluyen la
            opción {'"'}apuesta de pie{'"'} para cualquier asiento en la mesa,
            donde la persona puede esperar el asiento disponible.
          </p>

          <p className={styles.textP}>
            Asimismo, se pueden realizar apuestas paralelas que incluyen
            apuestas de {'"'}21+3{'"'} y {'"'}Perfect Paris{'"'}
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Qué se debe tener en cuenta a la hora de elegir donde jugar
            blackjack en vivo?
          </h1>

          <p className={styles.textP}>
            Hay factores que serán decisivos a la hora de elegir la mejor opción
            para aquellos que gustan de jugar blackjack.
          </p>

          <ul className={styles.list}>
            <li className={styles.ruletaListItem}>
              <strong>Velocidad en los pagos:</strong> Es importante que el
              cobro del dinero ganado pueda ser tan sencillo de realizar como
              fue ingresarlo al sistema. Un retiro de dinero rápido y sin
              problemas, sin dudas hará un casino digital muy recomendable.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Protección de fondos:</strong> Otro factor importante es
              que los datos personales cuenten con una alta seguridad. Esta es
              una de las inquietudes más grandes que tienen la mayoría de los
              jugadores que se registran en un casino digital con el fin de
              ganar algo de dinero. Por ello la mejor opción son los que tienen
              los mejores sistemas de seguridad de encriptación de datos.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Distintos tipos de juegos:</strong> Existen muchos tipos
              diferentes de Blackjack, es recomendable que investigues un poco
              las reglas de los mismos antes de aventurarte a elegir uno.
            </li>
          </ul>

          <p className={styles.textP}>
            Hay muchas maneras de disfrutar lo mejor del casino y desde la
            comodidad de tu casa, sin duda, cuando comiences a realizar tus
            apuestas de esta manera, ya nunca más querrás salir de tu casa a la
            hora de probar suerte con las apuestas.
          </p>
        </div>
      </div>

      <div className={styles.fixedDiv}>
        <div className={styles.fixedBox}>
          <form className={styles.subscritionForm}>
            <h3 className={styles.formHeader}>
              Subscribete para recibir descuentos y bonos
            </h3>
            <input
              className={styles.formInput}
              type="text"
              placeholder="Nombre"
            />
            <input
              className={styles.formInput}
              type="email"
              placeholder="Email"
            />
            <input
              className={styles.formInput}
              type="number"
              placeholder="Movil (opcional)"
            />
            <button className={styles.formBtn} type="submit">
              Suscribirse
            </button>
          </form>

          <div className={styles.fixedPromotedCasinosBox}>
            <h2 className={styles.fixedHeader}>Top 3 casinos</h2>

            {/** First Promoted Casino **/}
            <div className={styles.fixedPromotedCasinos}>
              <Image
                src="/favicon.ico"
                className={styles.casinoLogo}
                width={48}
                height={48}
                alt="Mega promoted casino"
              />
              <h3>Casino Pagando Duro</h3>
              <a className={styles.juegaCTA} href="#">
                Juega ahora!
              </a>
            </div>

            {/** Second Promoted Casino **/}
            <div className={styles.fixedPromotedCasinos}>
              <Image
                src="/favicon.ico"
                className={styles.casinoLogo}
                width={48}
                height={48}
                alt="Mega promoted casino"
              />
              <h3>Casino Pagando Duro</h3>
              <a className={styles.juegaCTA} href="#">
                Juega ahora!
              </a>
            </div>

            {/** Third Promoted Casino **/}
            <div className={styles.fixedPromotedCasinos}>
              <Image
                src="/favicon.ico"
                className={styles.casinoLogo}
                width={48}
                height={48}
                alt="Mega promoted casino"
              />
              <h3>Casino Pagando Duro</h3>
              <a className={styles.juegaCTA} href="#">
                Juega ahora!
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default blackjack;
