import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Blackjack.module.css";

function blackjack() {
  return (
    <div className={styles.hero}>
      <Head>
        <title>¿Cómo jugar Blackjack?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.textDiv}>
        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Cómo jugar blackjack?</h1>

          <p className={styles.textP}>
            Si eres nuevo en el mundo de las apuestas, seguramente te has
            preguntado
            <h2 className={styles.seoH2}>¿como jugar al blackjack y ganar?</h2>O
            al menos habrás escuchado nombrar este juego en películas donde los
            protagonistas contaban cartas y lograban hacerse de una probabilidad
            estadística de ganarle a la casa.
          </p>

          <p className={styles.textP}>
            Si bien, <h2 className={styles.seoH2}>jugar al blackjack</h2>, es
            sencillo comparado con otros juegos de mayor complejidad, requiere
            estar muy al tanto del reglamento para saber qué movimiento es el
            más conveniente en cada caso. Se juega con cartas francesas y el
            número de barajas a utilizar puede variar entre 1 y 8 según la
            versión del juego.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Cómo jugar al blackjack online?</h1>

          <p className={styles.textP}>
            <h2 className={styles.seoH2}>Jugar online blackjack</h2> es mucho
            más sencillo de lo que imaginas. Es posible jugar hasta 5 manos a la
            vez y con 5 apuestas individuales y diferentes, siempre irás contra
            la banca.
          </p>

          <p className={styles.textP}>
            Si bien hay muchos botones disponibles para realizar la jugada, la
            mayor parte del tiempo los mas usados serán {'"'}pedir{'"'},{'"'}
            repartir{'"'} y {'"'}plantarse{'"'}. Todas las opciones que hay son:
          </p>

          <ul className={styles.list}>
            <li className={styles.ruletaListItem}>
              <strong>Repartir:</strong> El botón indica al sistema que reparta
              las cartas. Es en este momento que el jugador recibe sus cartas.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Pedir:</strong> Indica al sistema que debe entregar más
              cartas al jugador.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Plantarse:</strong> En esta opción no recibirás más cartas
              y te quedas con la puntuación obtenida.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Doblar:</strong> Indica al sistema que doblas la apuesta y
              recibes una carta. Esta opción permite duplicar la apuesta inicial
              si se cumplen las siguientes circunstancias
            </li>
            <li className={styles.ruletaListItem}>
              Una vez que se ha repartido las primeras dos cartas se puede
              añadir una apuesta adicional igual a la apuesta original y solo
              podrás recibir una carta extra para completar la jugada.
            </li>
            <li className={styles.ruletaListItem}>
              Otra variante del juego la posibilidad de doblar una vez que se
              divide, también es necesario tener en cuenta
            </li>
            <li className={styles.ruletaListItem}>
              Una vez que divides una mano en dos aportes o más puedes doblar la
              apuesta a la mesa.
            </li>
            <li className={styles.ruletaListItem}>
              Si una vez que divides, decides doblar se comenzarán a aplicar las
              normas habituales para la opción doblar para ese momento.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Dividir:</strong>Cuando tienes dos cartas iguales, tienes
              la opción de jugar dos manos en una ronda.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Nueva apuesta:</strong> Comienzas una nueva ronda.
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Reapostar:</strong> vuelves a hacer la misma apuesta que
              en la ronda anterior
            </li>
            <li className={styles.ruletaListItem}>
              <strong>Rendirse:</strong> Algunos juegos de blackjack dan la
              opción de rendirse la cual permite recuperar el 50% de la apuesta
              inicial cuando es inminente que ganara la banca.
            </li>
          </ul>

          <p className={styles.textP}>
            Si todas estas indicaciones no alcanzan y aun así tienes dudas,
            dentro de las páginas hay una sección de ayuda donde hay preguntas
            frecuentes que hacen los usuarios y de este modo se puede seguir
            adelante con el juego de manera fluida.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Cuál es el objetivo del juego?</h1>

          <p className={styles.textP}>
            Aquí te explicaremos el:{" "}
            <h2 className={styles.seoH2}>como jugar al 21 blackjack</h2>. Se
            reparten dos cartas a la vista. El juego consiste en aproximarse al
            21 sin pasarse de la cifra, pero es necesario sobrepasar el valor
            que tiene el crupier para poder ganar la partida. Se considera
            blackjack cuando obtienes 21 puntos con tan solo 2 cartas, un as y
            una J, Q o K. Estas últimas valen 10 y 11 puntos el as. En caso de
            no llegar a 21 será necesaria obtener más de 21 puntos para poder
            ganar la partida. Un ejemplo muy gráfico sucede si sumas 18 puntos
            con tus cartas, la casa ganará si tiene 19, 20 o 21 puntos. En caso
            de empate se te devolverá la apuesta.
          </p>
          <p className={styles.textP}>
            El objetivo del Blackjack es derrotar a la banca y para ello es
            necesario tener una mano mejor que la de la banca y que esta no
            supere 21 en su sumatoria total. También es posible que ganes con
            menos de 22, pero la banca debe superar los 21. En caso de que tu
            mano pase de 22 se dice que te has {'"'}pasado{'"'} y puedes perder
            todo el dinero que apostaste.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Cuál es la mejor mano del juego?</h1>

          <p className={styles.textP}>
            La mejor mano del Blackjack es el {'"'}Blackjack{'"'} y tiene un
            premio superior que el de cualquier jugada y puede estar compuesta
            por un as y cualquier otra carta con valor de 10, reyes, jotas o
            damas. Es una jugada prácticamente invencible a no ser que empate a
            la banca.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Es posible contar cartas en el Blackjack?
          </h1>
          <p className={styles.textP}>
            El hecho de ser uno de los pocos juegos en los que se da esta
            posibilidad, ha hecho que muchos adeptos al juego lo intenten para
            hacer más rentables sus apuestas. Pero los casinos están muy al
            tanto de esta posible práctica y eso hace que tengan la precaución
            de realizar un mezclado constante y un cambio de barajas para evitar
            que aquellos que intenten contar cartas, tengan éxito.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Se puede seguir una estrategia exitosa en el blackjack?
          </h1>
          <p className={styles.textP}>
            En este juego a diferencia de otros más simples como las{" "}
            <strong>máquinas tragamonedas</strong> y la <strong>ruleta</strong>,
            en la que solo basta con apretar un botón, tomar la decisión
            correcta ayudará a minimizar la ventaja del casino
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Puedo jugar blackjack en vivo?</h1>
          <p className={styles.textP}>
            Está es una de las opciones más atractivas cuando comienzas en este
            mundo es la posibilidad de tener todo el realismo del blackjack
            presencial de un casino físico, pero en forma digital.
          </p>
        </div>
      </div>

      <div className={styles.fixedDiv}>
        <div className={styles.fixedBox}>
          <form className={styles.subscritionForm}>
            <h3 className={styles.formHeader}>
              Subscribete para recibir descuentos y bonos
            </h3>
            <input
              className={styles.formInput}
              type="text"
              placeholder="Nombre"
            />
            <input
              className={styles.formInput}
              type="email"
              placeholder="Email"
            />
            <input
              className={styles.formInput}
              type="number"
              placeholder="Movil (opcional)"
            />
            <button className={styles.formBtn} type="submit">
              Suscribirse
            </button>
          </form>

          <div className={styles.fixedPromotedCasinosBox}>
            <h2 className={styles.fixedHeader}>Top 3 casinos</h2>

            {/** First Promoted Casino **/}
            <div className={styles.fixedPromotedCasinos}>
              <Image
                src="/favicon.ico"
                className={styles.casinoLogo}
                width={48}
                height={48}
                alt="Mega promoted casino"
              />
              <h3>Casino Pagando Duro</h3>
              <a className={styles.juegaCTA} href="#">
                Juega ahora!
              </a>
            </div>

            {/** Second Promoted Casino **/}
            <div className={styles.fixedPromotedCasinos}>
              <Image
                src="/favicon.ico"
                className={styles.casinoLogo}
                width={48}
                height={48}
                alt="Mega promoted casino"
              />
              <h3>Casino Pagando Duro</h3>
              <a className={styles.juegaCTA} href="#">
                Juega ahora!
              </a>
            </div>

            {/** Third Promoted Casino **/}
            <div className={styles.fixedPromotedCasinos}>
              <Image
                src="/favicon.ico"
                className={styles.casinoLogo}
                width={48}
                height={48}
                alt="Mega promoted casino"
              />
              <h3>Casino Pagando Duro</h3>
              <a className={styles.juegaCTA} href="#">
                Juega ahora!
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default blackjack;
