import React from "react";
import Head from "next/head";

function casinos() {
  return (
    <div>
      <Head>
        <title>¿Cómo Escoger un Casino Online?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Aqui tenemos la pagina de casinos</h1>
    </div>
  );
}

export default casinos;
