import React from "react";
import Head from "next/head";

function guias() {
  return (
    <div>
      <Head>
        <title>Caracteristicas de un casino online entretenido</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Aqui tenemos la pagina de guias</h1>
    </div>
  );
}

export default guias;
