import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Ruleta.module.css";
import { Table } from "semantic-ui-react";

function ruleta() {
  return (
    <div className={styles.hero}>
      <Head>
        <title>¿Cómo jugar ruleta?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.textDiv}>
        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Cómo jugar ruleta online?</h1>
          <p className={styles.textP}>
            Si hablamos de Casinos Online, debemos hablar de ruletas. El juego
            de la ruleta es uno de los juegos más famosos y clásicos de los
            casinos alrededor de todo el mundo.
          </p>
          <p className={styles.textP}>
            El juego de la ruleta fue originalmente llamado Roulette en francés
            y fue inventado, según creen algunos historiadores, por el
            matemático Blaise Pascal en el siglo 17, combinando juegos
            anteriores mientras practicaba con máquinas de movimiento y
            siguiendo su afición matemática. Por lo que seguro que te estarás
            preguntando
            <h2 className={styles.seoH2}>¿Como jugar a la ruleta?</h2>Y lo
            primero que que tienes que tener claro es que es un juego de
            probabilidades y que estas no cambiaran por más tiradas que hagas.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Cuál es la diferencia entre la ruleta presencial y la digital?
          </h1>
          <p className={styles.textP}>
            El juego consta de un tablero sobre el cual hacemos nuestras
            apuestas, además de una bola y la ruleta propiamente dicha. En su
            versión de <h3 className={styles.seoH2}>ruleta casino online</h3>
            tendremos los mismos elementos aunque de tipo electrónico. Cuando la
            ruleta comienza a girar la bola es lanzada y frenará en un número,
            que posee también un color. Si acertamos en nuestra apuesta
            ganaremos de acuerdo a una tabla de premios.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            Lo clave para como saber jugar a la ruleta
          </h1>
          <ul className={styles.list}>
            <li className={styles.ruletaListItem}>
              Las apuestas de cada jugador pueden ser múltiples, por ejemplo,
              apostando a distintos números, color o zonas del tablero.
            </li>
            <li className={styles.ruletaListItem}>
              La ruleta consta de los números 0 al 36, siendo en total 37
              números al incluir el cero. Por lo que la probabilidad que salga
              un número en particular es de 1 en 37.
            </li>
            <li className={styles.ruletaListItem}>
              Los colores son Rojo y Negro. Hay 18 números de cada uno más el 0
              que es verde.
            </li>
          </ul>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Cómo varían los premios en la ruleta?
          </h1>
          <p className={styles.textP}>
            Los premios obtenidos si acertamos en la apuesta varían de acuerdo a
            la probabilidad de que ganemos. Por ejemplo, al apostar color nos
            retornará el doble de lo apostado, y la probabilidad es de casi la
            mitad: 18 de 37 números.
          </p>
          <p className={styles.textP}>
            Esa mecánica sucede con cada apuesta posible: solo la existencia del
            número 0, de color verde, evita que las apuestas sean un empate
            estadístico. Seguro te preguntaras
            <h2 className={styles.seoH2}>
              “¿cómo ganar dinero en la ruleta online?{'"'}
            </h2>
            Y realmente necesitamos suerte o intuición, aunque muchos jugadores
            estudian la existencia de patrones y hasta técnicas de victoria como
            la famosa Martingala: duplicar nuestra apuesta a color hasta
            finalmente ganar y recuperar lo perdido.
          </p>
        </div>

        <div className={styles.winChartDiv}>
          <Table className={styles.table}>
            <Table.Header>
              <Table.Row className={styles.tableRow}>
                <Table.HeaderCell className={styles.tableHead}>
                  Tipos de Apuesta
                </Table.HeaderCell>
                <Table.HeaderCell className={styles.tableHead}>
                  Retorno
                </Table.HeaderCell>
              </Table.Row>
            </Table.Header>

            <Table.Body>
              <Table.Row className={styles.tableRow}>
                <Table.Cell>Rojo/Negro</Table.Cell>
                <Table.Cell className={styles.tableWin}>x2</Table.Cell>
              </Table.Row>

              <Table.Row className={styles.tableRow}>
                <Table.Cell>Par/Impar</Table.Cell>
                <Table.Cell className={styles.tableWin}>x2</Table.Cell>
              </Table.Row>

              <Table.Row className={styles.tableRow}>
                <Table.Cell>Mitad Inferior/Superior</Table.Cell>
                <Table.Cell className={styles.tableWin}>x2</Table.Cell>
              </Table.Row>

              <Table.Row className={styles.tableRow}>
                <Table.Cell>Doble Docena / Doble Columna</Table.Cell>
                <Table.Cell className={styles.tableWin}>x1.5</Table.Cell>
              </Table.Row>

              <Table.Row className={styles.tableRow}>
                <Table.Cell>Docena o Columna</Table.Cell>
                <Table.Cell className={styles.tableWin}>x3</Table.Cell>
              </Table.Row>

              <Table.Row className={styles.tableRow}>
                <Table.Cell>Seisena</Table.Cell>
                <Table.Cell className={styles.tableWin}>x6</Table.Cell>
              </Table.Row>

              <Table.Row className={styles.tableRow}>
                <Table.Cell>
                  Cuadro(4 números) o Esquina (números 0 a 3)
                </Table.Cell>
                <Table.Cell className={styles.tableWin}>x9</Table.Cell>
              </Table.Row>

              <Table.Row className={styles.tableRow}>
                <Table.Cell>Transversal (línea)</Table.Cell>
                <Table.Cell className={styles.tableWin}>x12</Table.Cell>
              </Table.Row>

              <Table.Row className={styles.tableRow}>
                <Table.Cell>Caballo (2 números)</Table.Cell>
                <Table.Cell className={styles.tableWin}>x18</Table.Cell>
              </Table.Row>

              <Table.Row className={styles.tableRow}>
                <Table.Cell>Pleno (1 número)</Table.Cell>
                <Table.Cell className={styles.tableWin}>x36</Table.Cell>
              </Table.Row>
            </Table.Body>
          </Table>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Qué variantes de ruletas existen?
          </h1>
          <p className={styles.textP}>
            Existen varios tipos de ruleta de casino y cada una tiene una
            particularidad que la diferencia a continuación te explico la
            diferencia entre unas y otras.
          </p>

          <h2 className={styles.textHead}>
            ¿Como jugar a la ruleta americana?
          </h2>
          <p className={styles.textP}>
            Esta es una de las variantes más populares y la principal diferencia
            está dada por la rueda de la ruleta la cual cuenta con un doble cero
            a diferencia de la francesa y europea, pero esto solo aumenta las
            probabilidades de que gane la casa un 5,2%
          </p>

          <h2 className={styles.textHead}>¿Como jugar a la ruleta Europea?</h2>
          <p className={styles.textP}>
            Esta es una gran opción si buscas una ruleta que tenga pocas
            posibilidades de darle la ganancia a la casa, ya que aquí es del
            2,7% la ruleta contiene números del 1 al 36 y solo 1 cero. El
            jugador pueden apostar a números, colores, pares/impares entre
            muchas posibilidades.
          </p>

          <h2 className={styles.textHead}>Ruleta francesa</h2>
          <p className={styles.textP}>
            Es muy similar a la Europea y se rige por dos reglas especiales. Una
            de ellas es “la portage” que le da la posibilidad al apostador de
            recuperar su apuesta si pierde una apuesta externa cuando la bola da
            en el cero. La otra opción es {'"'}en prisión{'"'} te da la
            oportunidad de recuperar todas tus apuestas si la bola aterriza en
            cero. Esto hace que la probabilidad de la casa en un 1,35%
          </p>

          <h2 className={styles.textHead}>Ruleta múltiple</h2>
          <p className={styles.textP}>
            Esta es una gran opción si buscas una ruleta que tenga pocas
            posibilidades de darle la ganancia a la casa, ya que aquí es del
            2,7% la ruleta contiene números del 1 al 36 y solo 1 cero. El
            jugador pueden apostar a números, colores, pares/impares entre
            muchas posibilidades.
          </p>

          <h2 className={styles.textHead}>Ruleta en directo con crupier</h2>
          <p className={styles.textP}>
            Esta es sin dudas la opción más vistosa para aquellos que gustan de
            jugar de manera lo más cercana posible a la realidad, ya que muestra
            imágenes en vivo transmitidas de una de las mesas y da la
            posibilidad de apostar sobre lo que ocurre en la partida.
          </p>

          <p className={styles.textP}>
            A pesar de ser un juego aparentemente sencillo, la ruleta conquista
            el corazón de jugadores alrededor de todo el mundo, siendo un juego
            vibrante y demandado sin importar los años que pasen. Anímate a
            probar tu suerte.
          </p>
        </div>
      </div>

      <div className={styles.fixedDiv}>
        <div className={styles.fixedBox}>
          <form className={styles.subscritionForm}>
            <h3 className={styles.formHeader}>
              Subscribete para recibir descuentos y bonos
            </h3>
            <input
              className={styles.formInput}
              type="text"
              placeholder="Nombre"
            />
            <input
              className={styles.formInput}
              type="email"
              placeholder="Email"
            />
            <input
              className={styles.formInput}
              type="number"
              placeholder="Movil (opcional)"
            />
            <button className={styles.formBtn} type="submit">
              Suscribirse
            </button>
          </form>

          <div className={styles.fixedPromotedCasinosBox}>
            <h2 className={styles.fixedHeader}>Top 3 casinos</h2>

            {/** First Promoted Casino **/}
            <div className={styles.fixedPromotedCasinos}>
              <Image
                src="/favicon.ico"
                className={styles.casinoLogo}
                width={48}
                height={48}
                alt="Mega promoted casino"
              />
              <h3>Casino Pagando Duro</h3>
              <a className={styles.juegaCTA} href="#">
                Juega ahora!
              </a>
            </div>

            {/** Second Promoted Casino **/}
            <div className={styles.fixedPromotedCasinos}>
              <Image
                src="/favicon.ico"
                className={styles.casinoLogo}
                width={48}
                height={48}
                alt="Mega promoted casino"
              />
              <h3>Casino Pagando Duro</h3>
              <a className={styles.juegaCTA} href="#">
                Juega ahora!
              </a>
            </div>

            {/** Third Promoted Casino **/}
            <div className={styles.fixedPromotedCasinos}>
              <Image
                src="/favicon.ico"
                className={styles.casinoLogo}
                width={48}
                height={48}
                alt="Mega promoted casino"
              />
              <h3>Casino Pagando Duro</h3>
              <a className={styles.juegaCTA} href="#">
                Juega ahora!
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ruleta;
