import React from "react";
import Head from "next/head";
import styles from "../styles/Ruleta.module.css";

function ruleta() {
  return (
    <div className={styles.hero}>
      <Head>
        <title>¿Cómo jugar ruleta?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.textDiv}>
        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>¿Cómo jugar ruleta online?</h1>
          <p className={styles.textP}>
            Si hablamos de Casinos Online, debemos hablar de ruletas. El juego
            de la ruleta es uno de los juegos más famosos y clásicos de los
            casinos alrededor de todo el mundo.
          </p>
          <p className={styles.textP}>
            El juego de la ruleta fue originalmente llamado Roulette en francés
            y fue inventado, según creen algunos historiadores, por el
            matemático Blaise Pascal en el siglo 17, combinando juegos
            anteriores mientras practicaba con máquinas de movimiento y
            siguiendo su afición matemática. Por lo que seguro que te estarás
            preguntando
            {'"'}
            <h2 className={styles.seoH2}>¿Como jugar a la ruleta?</h2>
            {'"'} Y lo primero que que tienes que tener claro es que es un juego
            de probabilidades y que estas no cambiaran por más tiradas que
            hagas.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Cuál es la diferencia entre la ruleta presencial y la digital?
          </h1>
          <p className={styles.textP}>
            El juego consta de un tablero sobre el cual hacemos nuestras
            apuestas, además de una bola y la ruleta propiamente dicha. En su
            versión de <h3 className={styles.seoH2}>ruleta casino online</h3>
            tendremos los mismos elementos aunque de tipo electrónico. Cuando la
            ruleta comienza a girar la bola es lanzada y frenará en un número,
            que posee también un color. Si acertamos en nuestra apuesta
            ganaremos de acuerdo a una tabla de premios.
          </p>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            Lo clave para como saber jugar a la ruleta
          </h1>
          <ul className={styles.list}>
            <li className={styles.ruletaListItem}>
              Las apuestas de cada jugador pueden ser múltiples, por ejemplo,
              apostando a distintos números, color o zonas del tablero.
            </li>
            <li className={styles.ruletaListItem}>
              La ruleta consta de los números 0 al 36, siendo en total 37
              números al incluir el cero. Por lo que la probabilidad que salga
              un número en particular es de 1 en 37.
            </li>
            <li className={styles.ruletaListItem}>
              Los colores son Rojo y Negro. Hay 18 números de cada uno más el 0
              que es verde.
            </li>
          </ul>
        </div>

        <div className={styles.textContainer}>
          <h1 className={styles.textHead}>
            ¿Cómo varían los premios en la ruleta?
          </h1>
          <p className={styles.textP}>
            Los premios obtenidos si acertamos en la apuesta varían de acuerdo a
            la probabilidad de que ganemos. Por ejemplo, al apostar color nos
            retornará el doble de lo apostado, y la probabilidad es de casi la
            mitad: 18 de 37 números.
          </p>
          <p className={styles.textP}>
            Esa mecánica sucede con cada apuesta posible: solo la existencia del
            número 0, de color verde, evita que las apuestas sean un empate
            estadístico. Seguro te preguntaras
            <h2 className={styles.seoH2}>
              “¿cómo ganar dinero en la ruleta online?{'"'}
            </h2>
            Y realmente necesitamos suerte o intuición, aunque muchos jugadores
            estudian la existencia de patrones y hasta técnicas de victoria como
            la famosa Martingala: duplicar nuestra apuesta a color hasta
            finalmente ganar y recuperar lo perdido.
          </p>
        </div>
      </div>
    </div>
  );
}

export default ruleta;
